
services:
  backend:
      build:
        dockerfile: Dockerfile
        context: .
      restart: always
      ports:
        - 8080:8080
      env_file:
        - .env
      environment:
        - "POSTGRES_HOST=admin-db"

  bus:
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 2s
      timeout: 1s
