# fly.toml app configuration file generated for pixels-backend on 2024-08-25T22:29:59+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pixels-backend'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.22.3'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256MB'
  cpu_kind = 'shared'
  cpus = 1
  